//! Integration tests for rust-gnark Groth16 and PLONK BN254 prove/verify roundtrips.
//!
//! Uses pre-generated test vectors from a simple cubic circuit (x^3 + x + 5 == y, with x=3, y=35).
//! Test vectors are generated by `go/cmd/gen_test_vectors/main.go`.

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use rust_gnark::{groth16_prove, groth16_verify, init, plonk_prove, plonk_verify};

    const R1CS_PATH: &str = "./test-vectors/cubic_circuit.r1cs";
    const GROTH16_PK_PATH: &str = "./test-vectors/cubic_circuit.pk";
    const GROTH16_VK_PATH: &str = "./test-vectors/cubic_circuit.vk";

    const SCS_PATH: &str = "./test-vectors/cubic_circuit_plonk.scs";
    const PLONK_PK_PATH: &str = "./test-vectors/cubic_circuit_plonk.pk";
    const PLONK_VK_PATH: &str = "./test-vectors/cubic_circuit_plonk.vk";

    const WITNESS_JSON: &str = r#"{"X": "3", "Y": "35"}"#;

    // --- Groth16 tests ---

    #[test]
    fn test_groth16_prove_verify_roundtrip() -> Result<()> {
        init()?;

        let proof_result = groth16_prove(R1CS_PATH, GROTH16_PK_PATH, WITNESS_JSON)?;

        assert!(!proof_result.proof.is_empty(), "Proof should not be empty");
        assert!(
            !proof_result.public_inputs.is_empty(),
            "Public inputs should not be empty"
        );

        let valid = groth16_verify(R1CS_PATH, GROTH16_VK_PATH, &proof_result)?;
        assert!(valid, "Proof should be valid");

        Ok(())
    }

    #[test]
    fn test_groth16_verify_rejects_tampered_proof() -> Result<()> {
        init()?;

        let mut proof_result = groth16_prove(R1CS_PATH, GROTH16_PK_PATH, WITNESS_JSON)?;

        let mut chars: Vec<char> = proof_result.proof.chars().collect();
        if chars.len() > 10 {
            chars[10] = if chars[10] == 'a' { 'b' } else { 'a' };
        }
        proof_result.proof = chars.into_iter().collect();

        let result = groth16_verify(R1CS_PATH, GROTH16_VK_PATH, &proof_result);
        if let Ok(valid) = result {
            assert!(!valid, "Tampered proof should not be valid");
        }

        Ok(())
    }

    // --- PLONK tests ---

    #[test]
    fn test_plonk_prove_verify_roundtrip() -> Result<()> {
        init()?;

        let proof_result = plonk_prove(SCS_PATH, PLONK_PK_PATH, WITNESS_JSON)?;

        assert!(!proof_result.proof.is_empty(), "Proof should not be empty");
        assert!(
            !proof_result.public_inputs.is_empty(),
            "Public inputs should not be empty"
        );

        let valid = plonk_verify(SCS_PATH, PLONK_VK_PATH, &proof_result)?;
        assert!(valid, "Proof should be valid");

        Ok(())
    }

    #[test]
    fn test_plonk_verify_rejects_tampered_proof() -> Result<()> {
        init()?;

        let mut proof_result = plonk_prove(SCS_PATH, PLONK_PK_PATH, WITNESS_JSON)?;

        let mut chars: Vec<char> = proof_result.proof.chars().collect();
        if chars.len() > 10 {
            chars[10] = if chars[10] == 'a' { 'b' } else { 'a' };
        }
        proof_result.proof = chars.into_iter().collect();

        let result = plonk_verify(SCS_PATH, PLONK_VK_PATH, &proof_result);
        if let Ok(valid) = result {
            assert!(!valid, "Tampered proof should not be valid");
        }

        Ok(())
    }
}
